// This file is auto-generated by the 'collect_translations.py' script - do not edit it directly!

import "package:flutter/material.dart";

const List<Locale> supported_locales = [
    Locale("en", ""),   // Translations available in app_en.arb
    Locale("ru", "RU"),   // Translations available in app_ru_RU.arb
];
